CREATE TABLE products (
    ID SERIAL PRIMARY KEY,
    NAME TEXT NOT NULL,
    PRICE REAL NOT NULL,
    QUANTITY INT NOT NULL
);

INSERT INTO products ( NAME, PRICE, QUANTITY)
VALUES( 'TV SAMSUNG 50 POL', 2229.00, 34 );

INSERT INTO products ( NAME, PRICE, QUANTITY)
VALUES( 'MONITOR DELL 27 POL ', 1119.00, 11 );

INSERT INTO products ( NAME, PRICE, QUANTITY)
VALUES( 'MOUSE LOGITECH MK 233', 129.00, 19 );

INSERT INTO products ( NAME, PRICE, QUANTITY)
VALUES( 'XBOX SERIES S', 1999.00, 37 );

INSERT INTO products ( NAME, PRICE, QUANTITY)
VALUES( 'PLAYSTATION 5', 4299.00, 6 );
